language: node_js

node_js: lts/*

cache: npm

install:
  - npm ci
  - npm install -g codecov

script:
  - npm run lint
  - npm test
  - npm run build
  - npm run docs:build
  - codecov

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: .vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
